version: '3.8'

services:
  postgres: 
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=anyery
      - POSTGRES_PASSWORD=1187269
      - POSTGRES_DB=anyery
      - DATABASE_HOST=127.0.0.1

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "anyery@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "1187269"
    ports:
      - "80:80"
    depends_on:
      - postgres

  nginx:
    image: nginx
    volumes:
      - ./static:/usr/share/nginx/html
    ports:
      - "8080:80"
